### ISSUE TITLE
Replay buffer for PPO

### ISSUE THREAD

**Issue by oribarel** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#3]
Do you have any plans to add a replay buffer for PPO?

**Comment by p-christ** [comment]
Hi! 

I don't at the moment as I didn't realise using a replay buffer with PPO was much of an option - is that something you've seen work somewhere?  

I would think that because PPO generates new experiences in parallel it can get new data very fast and so there's less need for something like a replay buffer but it could still be worth trying and it wouldn't be that hard to implement

**Comment by oribarel** [comment]
Maybe I didn't get it, but isn't a replay buffer is used here https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-PPO.md#buffer-size ?

**Comment by p-christ** [comment]
I'm not 100% sure as I think there are often multiple ways of writing these algorithms, but I think by "buffer size" there they just mean the amount of experience you should collect before doing learning.  In the PPO model we still collect experience, it's just we don't put it in a replay buffer because we use it immediately and then throw it away and so there's no need to store it somewhere.
